#!/usr/bin/env python3
"""Generate the embedded catalog; --check rejects a stale generated header."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ('en', 'zh-CN', 'zh-TW', 'ja', 'ko')

def generate():
    catalogs = [json.loads((ROOT / 'linux/i18n' / (language + '.json')).read_text())
                for language in LANGUAGES]
    keys = sorted(catalogs[0])
    for language, catalog in zip(LANGUAGES, catalogs):
        if set(catalog) != set(keys):
            raise ValueError(f'{language}: inconsistent message coverage')
    quote = lambda text: json.dumps(text, ensure_ascii=False)
    rows = [f'    {{{quote(key)}, {{{", ".join(quote(c[key]) for c in catalogs)}}}}},'
            for key in keys]
    return ('/* Generated by scripts/generate_cli_messages.py; edit the JSON catalogs in linux/i18n. */\n'
            '#ifndef NEKOKEM_CLI_MESSAGES_H\n#define NEKOKEM_CLI_MESSAGES_H\n'
            'static const struct { const char *source; const char *translated[5]; } messages[] = {\n'
            + '\n'.join(rows) + '\n};\n#endif\n')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'linux/src/messages.h'
    text = generate()
    if args.check:
        if not path.exists() or path.read_text() != text:
            raise SystemExit('Generated CLI catalog is stale; run scripts/generate_cli_messages.py')
    else:
        path.write_text(text)
